FROM python:3.11-slim AS base

WORKDIR /app

COPY pyproject.toml poetry.lock /app/

RUN pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-dev --no-root --no-interaction --no-ansi

FROM base AS worker

COPY app /app/app
COPY alembic.ini /app/alembic.ini

ENV PYTHONPATH="${PYTHONPATH}:/app"

CMD ["python3", "app/worker.py"]
